name: Build and Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Docker build
        run: docker build -t linkedin-coldmessages .
